- name: Install Additional Dev libriaries
  dnf:
    name:
      - '@Development tools' 
      - pcre-devel
      - zlib-devel
      - openssl-devel
      - python3-devel
      - mysql-devel
    state: present
